### ISSUE TITLE
I updated lr-bluemsx on my Pi4B and now it won't start

### ISSUE THREAD

**Issue by dukeforestPi** [libretro/blueMSX-libretro#163]
I updated on a Pi 4B and it gives me an error and won't start.
Here is the part of the error in the log

/opt/retropie/supplementary/runcommand/runcommand.sh: line 1319: 11828 Segmentation fault

**Comment by zoltanvb** [comment]
Thank you for reporting! Please update again, #164 should fix it.

**Comment by RickDangerousPi** [comment]
Issue still remains, I have exact same problem which effects launching msx2 reverting core is the only way i can get them to load.

**Comment by RickDangerousPi** [comment]
Updating from source fixed it!

**Comment by dukeforestPi** [comment]
I have updated it and it is working fine!
Thanks a lot.
